version: '2'
services:
    runes:
        build: .
        command: runes start --config /root/conf/runes.yaml
        ports:
            - "127.0.0.1:8086:8086"
        volumes:
            - ./conf:/root/conf
            - ./data:/root/data

